baseURL = "https://lorendb.dev"
languageCode = 'en-us'
title = "Loren's blog"
theme = "m10c"
paginate = 8
copyright = "© Loren Burkholder"

[params]
  description = "Programming, selfhosting, and general tech stuff"
  menu_item_separator = " - "
  avatar = "/avatar.jpeg"
  author.name = "Loren Burkholder"
  author.link = "https://lorendb.dev"
  author.email = "computersemiexpert@outlook.com"
  images = ["images/opengraph-placeholder.png"]
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/LorenDB"
  [[params.social]]
    icon = "hash"
    name = "Matrix"
    url = "https://matrix.to/#/@lorendb:nheko.im"
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:computersemiexpert@outlook.com"
  [[params.social]]
    icon = "rss"
    name = "RSS feed"
    url = "https://lorendb.dev/index.xml"
